import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import MouseFollower from "@/components/common/MouseFollower";

const soraFont = Sora({
  subsets: ["latin"],
  display: "swap"
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
        className={` ${soraFont.className} bg-color text-white/60 relative`}
        >
        <ClerkProvider>
          <Toaster/>
          <MouseFollower/>
          <Navbar/>
        {/* <div className="neon absolute top-0 left-0 size-[45rem] bg-purple-500 blur-[20rem]"/> */}
          
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
